/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni_jdk1_6_24\jni.h"
#include "jni_jdk1_6_24\jni_md.h"
#include "jni_jdk1_6_24\jawt_md.h"
/* Header for class org_jwebtop_JWebTopNative */

#ifndef _Included_org_jwebtop_JWebTopNative
#define _Included_org_jwebtop_JWebTopNative
#ifdef __cplusplus

extern "C" {
#endif

	// dll入口函数
	BOOL APIENTRY DllMain(HMODULE hModule, DWORD  dwReason, LPVOID lpReserved);
	/*
	 * 对应org.jwebtop.JWebTopNative类的nCreateJWebTop方法
	 * 该方法用于创建一个浏览器窗口
	 * processPath 待执行的JWebTop.exe的全路径。比如d:\c\JWebTop.exe，当然JWebTop可以命名为其他名字。
	 * configFile  此配置文件用于启动JWebTop进程（但，不立刻创建浏览器窗口，即使指定了url参数）
	 * parentWin   创建的浏览器的父窗口是哪个
	 */
	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nCreateJWebTop
		(JNIEnv *, jclass, jstring processPath, jstring configFile);

	/*
	* 对应org.jwebtop.JWebTopNative类的nCreateBrowser方法
	* 该方法用于创建一个浏览器窗口
	* jWebTopConfigJSON 浏览器配置信息JSON(JWebTopConfigs.h)
	*
	* return 返回创建的浏览器窗口的句柄
	*/
	JNIEXPORT jlong JNICALL Java_org_jwebtop_JWebTopNative_nCreateBrowser
		(JNIEnv * env, jclass, jstring jWebTopConfigJSON);

   /*
	* 对应org.jwebtop.JWebTopNative类的nCloseBrowser方法
	* 该方法用于关闭一个浏览器窗口
	* browserHWnd  浏览器窗口句柄
	*/
	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nCloseBrowser
		(JNIEnv * env, jclass, jlong browserHWnd);
	/*
	 * 下面四个方法用于执行浏览器脚本
	 */
	JNIEXPORT jstring JNICALL Java_org_jwebtop_JWebTopNative_nExecuteJSWait
		(JNIEnv *, jclass, jlong browserHWnd, jstring script);
	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nExecuteJSNoWait
		(JNIEnv *, jclass, jlong browserHWnd, jstring script);
	JNIEXPORT jstring JNICALL Java_org_jwebtop_JWebTopNative_nExecuteJSONWait
		(JNIEnv *, jclass, jlong browserHWnd, jstring json);
	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nExecuteJSONNoWait
		(JNIEnv *, jclass, jlong browserHWnd, jstring json);

	// jni方法：设置窗口大小
	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nSetSize
		(JNIEnv *, jclass, jlong browserHWnd, jint w, jint h);
	JNIEXPORT jintArray JNICALL Java_org_jwebtop_JWebTopNative_nGetSize
		(JNIEnv *, jclass, jlong browserHWnd);
	JNIEXPORT jintArray JNICALL Java_org_jwebtop_JWebTopNative_nGetScreenSize
		(JNIEnv *, jclass);

	// jni方法：设置窗口位置
	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nSetLocation
		(JNIEnv *, jclass, jlong browserHWnd, jint x, jint y);
	JNIEXPORT jintArray JNICALL Java_org_jwebtop_JWebTopNative_nGetLocation
		(JNIEnv *, jclass, jlong browserHWnd);

	// jni方法：设置窗口位置和大小
	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nSetBound
		(JNIEnv *, jclass, jlong browserHWnd, jint x, jint y, int w, int h);
	JNIEXPORT jintArray JNICALL Java_org_jwebtop_JWebTopNative_nGetBound
		(JNIEnv *, jclass, jlong browserHWnd);

	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nBringToTop
		(JNIEnv *, jclass, jlong browserHWnd);//窗口移到最顶层
	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nFocus
		(JNIEnv *, jclass, jlong browserHWnd);//使窗口获得焦点
	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nHide
		(JNIEnv *, jclass, jlong browserHWnd);//隐藏窗口
	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nMax
		(JNIEnv *, jclass, jlong browserHWnd);//最大化窗口
	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nMini
		(JNIEnv *, jclass, jlong browserHWnd);//最小化窗口
	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nRestore
		(JNIEnv *, jclass, jlong browserHWnd);//还原窗口，对应于hide函数
	JNIEXPORT jboolean JNICALL Java_org_jwebtop_JWebTopNative_nIsVisible
		(JNIEnv *, jclass, jlong browserHWnd);// 窗口是否显示
	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nSetTopMost
		(JNIEnv *, jclass, jlong browserHWnd);//窗口置顶，此函数跟bringToTop的区别在于此函数会使窗口永远置顶，除非有另外一个窗口调用了置顶函数


	// jni方法：退出JWebTop进程
	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nExit
		(JNIEnv *, jclass);

	JNIEXPORT jintArray Java_org_jwebtop_JWebTopNative_nGetWindowClient(JNIEnv *, jclass,jlong hWnd);
#ifdef __cplusplus
}
#endif
#endif
