/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni_jdk1_6_24\jni.h"
//#include "jni_jdk1_6_24\jni_md.h"
//#include "jni_jdk1_6_24\jawt_md.h"
/* Header for class org_jwebtop_JWebTopNative */

#ifndef _Included_org_jwebtop_JWebTopNative
#define _Included_org_jwebtop_JWebTopNative
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * 获取最前端窗口
	 */
	JNIEXPORT jlong JNICALL Java_org_jwebtop_JWebTopNative_nGetForegroundWindow(JNIEnv * env, jclass);

	/*
	 * 按指定风格显示窗口
	 */
	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nShowWindow(JNIEnv * env, jclass, jlong, jint);

	// 创建一个新进程，返回的数据为进程中主线程的id
	JNIEXPORT jlong JNICALL Java_org_jwebtop_JWebTopNative_nCreateSubProcess(JNIEnv * env, jclass, jstring subProcess, jstring szCmdLine,jboolean waitFor);
	
	/*
	* 获取当前进程id
	*
	* return 返回当前进程id
	*/
	JNIEXPORT jlong JNICALL Java_org_jwebtop_JWebTopNative_nGetProcessID
		(JNIEnv * env, jclass);

	// jni方法：设置窗口大小
	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nSetSize
		(JNIEnv *, jclass, jlong browserHWnd, jint w, jint h);
	JNIEXPORT jintArray JNICALL Java_org_jwebtop_JWebTopNative_nGetSize
		(JNIEnv *, jclass, jlong browserHWnd);
	JNIEXPORT jintArray JNICALL Java_org_jwebtop_JWebTopNative_nGetScreenSize
		(JNIEnv *, jclass);

	// jni方法：设置窗口位置
	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nSetLocation
		(JNIEnv *, jclass, jlong browserHWnd, jint x, jint y);
	JNIEXPORT jintArray JNICALL Java_org_jwebtop_JWebTopNative_nGetLocation
		(JNIEnv *, jclass, jlong browserHWnd);

	// jni方法：设置窗口位置和大小
	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nSetBound
		(JNIEnv *, jclass, jlong browserHWnd, jint x, jint y, int w, int h);
	JNIEXPORT jintArray JNICALL Java_org_jwebtop_JWebTopNative_nGetBound
		(JNIEnv *, jclass, jlong browserHWnd);

	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nBringToTop
		(JNIEnv *, jclass, jlong browserHWnd);//窗口移到最顶层
	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nFocus
		(JNIEnv *, jclass, jlong browserHWnd);//使窗口获得焦点
	JNIEXPORT jboolean JNICALL Java_org_jwebtop_JWebTopNative_nIsVisible
		(JNIEnv *, jclass, jlong browserHWnd);// 窗口是否显示
	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nSetTopMost
		(JNIEnv *, jclass, jlong browserHWnd);//窗口置顶，此函数跟bringToTop的区别在于此函数会使窗口永远置顶，除非有另外一个窗口调用了置顶函数
	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nSetWindowStyle
		(JNIEnv *, jclass, jlong browserHWnd, jint style);
	JNIEXPORT void JNICALL Java_org_jwebtop_JWebTopNative_nSetWindowExStyle
		(JNIEnv *, jclass, jlong browserHWnd, jint exStyle);
	JNIEXPORT jintArray Java_org_jwebtop_JWebTopNative_nGetWindowClient(JNIEnv *, jclass,jlong hWnd);
#ifdef __cplusplus
}
#endif
#endif
