#ifndef CEF_JWEBTOP_JS_HANDLER_H_
#define CEF_JWEBTOP_JS_HANDLER_H_

#include <sstream>
#include <string>
#include "include/cef_app.h" 
const std::string  jsCode = "var JWebTop;"
"if (!JWebTop)"
"  JWebTop = {};"
"(function() {"
"  JWebTop.close = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function close(handler);"
"    return close(handler);"
"  };"
"  JWebTop.stopDrag = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function stopDrag(handler);"
"    return stopDrag(handler);"
"  };"
"  JWebTop.setSize = function(w,h,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function setSize(handler,w,h);"
"    return setSize(handler,w,h);"
"  };"
"  JWebTop.move = function(x,y,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function move(handler,x,y);"
"    return move(handler,x,y);"
"  };"
"  JWebTop.max = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function max(handler);"
"    return max(handler);"
"  };"
"  JWebTop.hide = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function hide(handler);"
"    return hide(handler);"
"  };"
"  JWebTop.mini = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function mini(handler);"
"    return mini(handler);"
"  };"
"  JWebTop.setBound = function(x,y,w,h,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function setBound(handler);"
"    return setBound(handler,x,y,w,h);"
"  };"
"  JWebTop.restore = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function restore(handler);"
"    return restore(handler);"
"  };"
"  JWebTop.drag = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function drag(handler);"
"    return drag(handler);"
"  };"
"  JWebTop.render = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function render(handler);"
"    return render(handler);"
"  };"
"  JWebTop.bringToTop = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function bringToTop(handler);"
"    return bringToTop(handler);"
"  };"
"  JWebTop.focus = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function focus(handler);"
"    return focus(handler);"
"  };"
"  JWebTop.loadUrl = function(url,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function loadUrl(handler,url);"
"    return loadUrl(handler,url);"
"  };"
"  JWebTop.getPos = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function getPos(handler);"
"    return getPos(handler);"
"  };"
"  JWebTop.getSize = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function getSize(handler);"
"    return getSize(handler);"
"  };"
"  JWebTop.enableDrag = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function enableDrag(handler);"
"    return enableDrag(handler);"
"  };"
"  JWebTop.quit = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function quit(handler);"
"    return quit(handler);"
"  };"
"  JWebTop.ready = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function ready(handler);"
"    return ready(handler);"
"  };"
"  JWebTop.createWindow = function(url,exStyle,isTransparent,readyHandler,handler) {"
"    handler=handler?handler:window['handler'];"
"    readyHandler=readyHandler||'';"
"    native function createWindow(handler,url,exStyle,isTransparent,readyHandler);"
"    return createWindow(handler,url,exStyle,isTransparent,readyHandler);"
"  };"
"  JWebTop.createWindowBase = function(url,exStyle,isTransparent,readyHandler,handler) {"
"    handler=handler?handler:window['handler'];"
"    readyHandler=readyHandler||'';"
"    native function createWindowBase(handler,url,exStyle,isTransparent,readyHandler);"
"    return createWindowBase(handler,url,exStyle,isTransparent,readyHandler);"
"  };"
"  JWebTop.createBrowser = function(url,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function createBrowser(handler,url);"
"    return createBrowser(handler,url);"
"  };"
"  JWebTop.browse = function(url,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function browse(handler,url);"
"    return browse(handler,url);"
"  };"
"  JWebTop.setTitle = function(title,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function setTitle(handler,title);"
"    return setTitle(handler,title);"
"  };"
"  JWebTop.getImage = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function getImage(handler);"
"    return getImage(handler);"
"  };"
"  JWebTop.showDev = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function showDev(handler);"
"    return showDev(handler);"
"  };"
"  JWebTop.readFile = function(path,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function readFile(handler,path);"
"    return readFile(handler,path);"
"  };"
"  JWebTop.writeFile = function(path,s,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function writeFile(handler,path,s);"
"    return writeFile(handler,path,s);"
"  };"
"  JWebTop.getSaveName = function(filename,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function getSaveName(handler,filename);"
"    return getSaveName(handler,filename);"
"  };"
"  JWebTop.runApp = function(appName,param,handler) {"
"    handler=handler?handler:window['handler'];"
"	 param=param?param:'';"
"    native function runApp(handler,appName,param);"
"    return runApp(handler,appName,param);"
"  };"
"  JWebTop.runAppEx = function(appName,param,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function runAppEx(handler,appName,param);"
"    return runAppEx(handler,appName,param);"
"  };"
"  JWebTop.download = function(url,filename,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function download(handler,url,filename);"
"    return download(handler,url,filename);"
"  };"
"  JWebTop.getOpenName = function(filename,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function getOpenName(handler,filename);"
"    return getOpenName(handler,filename);"
"  };"
"  JWebTop.getOpenNames = function(filename,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function getOpenNames(handler,filename);"
"    return JSON.parse(getOpenNames(handler,filename).replace(/\\\\/g,'\\\\\\\\'));"
"  };"
"  JWebTop.getFileSize = function(filename,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function getFileSize(handler,filename);"
"    return getFileSize(handler,filename);"
"  };"
"  JWebTop.getFolder = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function getFolder(handler);"
"    return getFolder(handler);"
"  };"
"  JWebTop.reload = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function reload(handler);"
"    return reload(handler);"
"  };"
"  JWebTop.reloadIgnoreCache = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function reloadIgnoreCache(handler);"
"    return reloadIgnoreCache(handler);"
"  };"
"  JWebTop.setTopMost = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function setTopMost(handler);"
"    return setTopMost(handler);"
"  };"
"  JWebTop.setWindowStyle = function(exStyle,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function setWindowStyle(handler,exStyle);"
"    return setWindowStyle(handler,exStyle);"
"  };"
"  JWebTop.getSharePos = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function getSharePos(handler);"
"    return getSharePos(handler);"
"  };"
"  JWebTop.setSharePos = function(i) {"
"    handler=handler?handler:window['handler'];"
"    native function setSharePos(handler,i);"
"    return setSharePos(handler,i);"
"  };"
"  JWebTop.toImageEx = function(path,x,y,width,height,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function toImageEx(handler,path,x,y,width,height);"
"    return toImageEx(handler,path,x,y,width,height);"
"  };"
"  JWebTop.toImage = function(path,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function toImage(handler,path);"
"    return toImage(handler,path);"
"  };"
"  JWebTop.shutdown = function(flag,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function shutdown(handler,flag);"
"    return shutdown(handler,flag);"
"  };"
"  JWebTop.reboot = function(flag,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function reboot(handler,flag);"
"    return reboot(handler,flag);"
"  };"
"  JWebTop.logoff = function(flag,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function logoff(handler,flag);"
"    return logoff(handler,flag);"
"  };"
"  JWebTop.connect = function(ip,uid,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function connect(handler,ip,uid);"
"    return connect(handler,ip,uid);"
"  };"
"  JWebTop.connectByHost = function(hostName,uid,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function connectByHost(handler,hostName,uid);"
"    return connectByHost(handler,hostName,uid);"
"  };"
"  JWebTop.getUsers = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function getUsers(handler);"
"    return getUsers(handler);"
"  };"
"  JWebTop.sendMessage = function(userName,msg,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function sendMessage(handler,userName,msg);"
"    return sendMessage(handler,userName,msg);"
"  };"
"  JWebTop.sendMsgToIP = function(ip,port,msg,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function sendMsgToIP(handler,ip,port,msg);"
"    return sendMsgToIP(handler,ip,port,msg);"
"  };"
"  JWebTop.sendMsgToServer = function(msg,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function sendMsgToServer(handler,msg);"
"    return sendMsgToServer(handler,msg);"
"  };"
"  JWebTop.getIPAndPort = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function getIPAndPort(handler);"
"    return getIPAndPort(handler);"
"  };"
"  JWebTop.setTaskIcon = function(id,path,title,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function setTaskIcon(handler,id,path,title);"
"    return setTaskIcon(handler,id,path,title);"
"  };"
"  JWebTop.delTaskIcon = function(id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function delTaskIcon(handler,id);"
"    return delTaskIcon(handler,id);"
"  };"
"  JWebTop.findFiles = function(path,flag,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function findFiles(handler,path,flag);"
"    return JSON.parse(findFiles(handler,path,flag));"
"  };"
"  JWebTop.getCurrentDirectory = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function getCurrentDirectory(handler);"
"    return getCurrentDirectory(handler);"
"  };"
"  JWebTop.createMemory = function(name,filename,size,handler) {"
"    handler=handler?handler:window['handler'];"
"	 filename=filename?filename:'';"
"    native function createMemory(handler,name,filename,size);"
"    return createMemory(handler,name,filename,size);"
"  };"
"  JWebTop.deleteMemory = function(id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function deleteMemory(handler,id);"
"    return deleteMemory(handler,id);"
"  };"
"  JWebTop.createStream = function(id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function createStream(handler,id);"
"    return createStream(handler,id);"
"  };"
"  JWebTop.deleteStream = function(id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function deleteStream(handler,id);"
"    return deleteStream(handler,id);"
"  };"
"  JWebTop.readString = function(l,id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function readString(handler,id,l);"
"    return readString(handler,id,l);"
"  };"
"  JWebTop.readGB = function(l,id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function readGB(handler,id,l);"
"    return readGB(handler,id,l);"
"  };"
"  JWebTop.writeString = function(s,id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function writeString(handler,id,s);"
"    return writeString(handler,id,s);"
"  };"
"  JWebTop.readWString = function(l,id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function readWString(handler,id,l);"
"    return readWString(handler,id,l);"
"  };"
"  JWebTop.writeWString = function(s,id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function writeWString(handler,id,s);"
"    return writeWString(handler,id,s);"
"  };"
"  JWebTop.readStringEx = function(l,id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function readStringEx(handler,id,l);"
"    return readStringEx(handler,id,l);"
"  };"
"  JWebTop.writeStringEx = function(s,id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function writeStringEx(handler,id,s);"
"    return writeStringEx(handler,id,s);"
"  };"
"  JWebTop.readWStringEx = function(l,id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function readWStringEx(handler,id,l);"
"    return readWStringEx(handler,id,l);"
"  };"
"  JWebTop.writeWStringEx = function(s,id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function writeWStringEx(handler,id,s);"
"    return writeWStringEx(handler,id,s);"
"  };"
"  JWebTop.readInt = function(id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function readInt(handler,id);"
"    return readInt(handler,id);"
"  };"
"  JWebTop.writeInt = function(i,id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function writeInt(handler,id,i);"
"    return writeInt(handler,id,i);"
"  };"
"  JWebTop.readByte = function(id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function readByte(handler,id);"
"    return readByte(handler,id);"
"  };"
"  JWebTop.writeByte = function(b,id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function writeByte(handler,id,b);"
"    return writeByte(handler,id,b);"
"  };"
"  JWebTop.readBytes = function(l,id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function readBytes(handler,id,l);"
"    return readBytes(handler,id,l);"
"  };"
"  JWebTop.writeBytes = function(arr,id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function writeBytes(handler,id,arr);"
"    return writeBytes(handler,id,arr);"
"  };"
"  JWebTop.setStreamPos = function(pos,id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function setStreamPos(handler,id,pos);"
"    return setStreamPos(handler,id,pos);"
"  };"
"  JWebTop.getStreamPos = function(id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function getStreamPos(handler,id);"
"    return getStreamPos(handler,id);"
"  };"
"  JWebTop.getStreamPos = function(id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function getStreamPos(handler,id);"
"    return getStreamPos(handler,id);"
"  };"
"  JWebTop.saveImageFromStream = function(id,width,height,path,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function saveImageFromStream(handler,id,width,height,path);"
"    return saveImageFromStream(handler,id,width,height,path);"
"  };"
"  JWebTop.saveImageFromBase64 = function(s,path,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function saveImageFromBase64(handler,s,path);"
"    return saveImageFromBase64(handler,s,path);"
"  };"
"  JWebTop.getScreenSize = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function getScreenSize(handler);"
"    return getScreenSize(handler);"
"  };"
"  JWebTop.shellExecute = function(operation,path,params,directory,cmdShow,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function shellExecute(handler,operation,path,params,directory,cmdShow);"
"    return shellExecute(handler,operation,path,params,directory,cmdShow);"
"  };"
"  JWebTop.winExec = function(cmd,cmdShow,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function winExec(handler,cmd,cmdShow);"
"    return winExec(handler,cmd,cmdShow);"
"  };"
"  JWebTop.execJS = function(js,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function execJS(handler,js);"
"    return execJS(handler,js);"
"  };"
"  JWebTop.createTcpServer = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function createTcpServer(handler);"
"    return createTcpServer(handler);"
"  };"
"  JWebTop.shutdownTcpServer = function(id,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function shutdownTcpServer(handler,id);"
"    return shutdownTcpServer(handler,id);"
"  };"
"  JWebTop.sendTcpMsg = function(id,msg,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function sendTcpMsg(handler,id,msg);"
"    return sendTcpMsg(handler,id,msg);"
"  };"
"  JWebTop.execJS = function(js,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function execJS(handler,js);"
"    return execJS(handler,js);"
"  };"
"  JWebTop.getIP = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function getIP(handler);"
"    return getIP(handler);"
"  };"
"  JWebTop.getLastMessage = function(handler) {"
"    handler=handler?handler:window['handler'];"
"    native function getLastMessage(handler);"
"    return getLastMessage(handler);"
"  };"
"  JWebTop.getMessage = function(timestamp,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function getMessage(handler,timestamp);"
"    return getMessage(handler,timestamp);"
"  };"
"  JWebTop.startProxy = function(port,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function startProxy(handler,port);"
"    return startProxy(handler,port);"
"  };"
"  JWebTop.closeProxy = function(proxy,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function closeProxy(handler,proxy);"
"    return closeProxy(handler,proxy);"
"  };"
"  JWebTop.replaceRequest = function(responseHandler,request,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function replaceRequest(handler,responseHandler,request);"
"    return replaceRequest(handler,responseHandler,request);"
"  };"
"  JWebTop.replaceResponse = function(responseHandler,response,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function replaceResponse(handler,responseHandler,response);"
"    return replaceResponse(handler,responseHandler,response);"
"  };"
"  JWebTop.response = function(responseHandler,responseContent,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function response(handler,responseHandler,responseContent);"
"    return response(handler,responseHandler,responseContent);"
"  };"
"  JWebTop.cancelReplaceResponse = function(responseHandler,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function cancelReplaceResponse(handler,responseHandler);"
"    return cancelReplaceResponse(handler,responseHandler);"
"  };"
"  JWebTop.cancelResponse = function(responseHandler,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function cancelResponse(handler,responseHandler);"
"    return cancelResponse(handler,responseHandler);"
"  };"
"  JWebTop.gb2utf8 = function(s,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function gb2utf8(handler,s);"
"    return gb2utf8(handler,s);"
"  };"
"  JWebTop.utf82gb = function(s,handler) {"
"    handler=handler?handler:window['handler'];"
"    native function utf82gb(handler,s);"
"    return utf82gb(handler,s);"
"  };"
"  JWebTop.invokeJava = function(s,handler) {"// 注册invokeJava函数到JWebTop对象
"    handler=handler?handler:window['handler'];"
"    native function invokeJava(handler,s);"
"    return invokeJava(handler,s);"
"  };"
"  JWebTop.invokeJSONMode = function(json,handler) {"// 注册invokeJava函数到JWebTop对象
"    handler=handler?handler:window['handler'];"
"    native function invokeJSONMode(handler,s);"
"    return invokeJava(handler,s);"
"  };"
"})();";
// Client app implementation for the renderer process.

class JJSHandler{

};

class JWebTopJSHandler : public CefV8Handler {
public:
	virtual bool Execute(const CefString& name,
		CefRefPtr<CefV8Value> object,
		const CefV8ValueList& arguments,
		CefRefPtr<CefV8Value>& retval,
		CefString& exception) OVERRIDE;

private:
	IMPLEMENT_REFCOUNTING(JWebTopJSHandler);
};

#endif  // CEF_JWEBTOP_JS_HANDLER_H_